version: '3.8'

services:
  nginx:
    image: caoweida2004/nginx-http3:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/nginx/html:ro
    restart: unless-stopped
